### ISSUE TITLE
Alt ID pages

### ISSUE THREAD

**Issue by marieALaporte** [Planteome/amigo#33]
Shouldn't the alt_id pages redirect to the main term?
Is it a normal behaviour to end up on this page during a search?
http://browser.planteome.org/amigo/term/PO:0006445

**Comment by elserj** [comment]
I don't think they should.  GO doesn't have them redirect either.  I think the issue with this term in particular is that PO:00006445 is only in the obo/owl files has an alternate id for PO:0000002, so all of the fields on the term page are empty.  I haven't found an older version of the file where it does exist, at least in the last 3 years.  I'll keep looking to see if I can find a version where it was there.  

It may just be a typo that got entered at some point.  I'll update if I find a commit where something was done with it.

**Comment by elserj** [comment]
Found it.  That one, and several others were all removed in commit https://github.com/Planteome/plant-ontology/commit/e15c804271a291ab8385897ab4607ed24e6ce63a back in 2011.  I would think it was a mistake to remove terms rather than obsolete them, but I'm not sure what the protocol is.

Tagging @cooperl09 for thoughts.

**Comment by cooperl09** [comment]
Our practice has always been to obsolete, rather than 'remove' which I interpret to mean 'delete'.
The link to the commit you posted above show a merge, not a deletion or removal the terms. 
Back in the OBO-Edit days this was done when two terms needed to be combined. In that case the ID of the term being merged in became the alt ID.  Although there is no definition etc, there is a "replaced by" link that the user can follow to the new term.

**Comment by elserj** [comment]
I defer to you guys on what to do, but I thought we left the full term stanza there with just an "is_obsolete" added so that when viewing on the browser, it didn't look so ... empty.
