### ISSUE TITLE
Display list of files loaded on Dev or Live

### ISSUE THREAD

**Issue by cooperl09** [Planteome/amigo#34]
It would be great if the page http://dev.planteome.org/amigo/load_details showed the actual list of files loaded without @elserj having to manually tweak it. This info is coming from a file in the web directory which is overridden by the catalog file. 

Can you tweak the loading script to read the catalog file (https://github.com/Planteome/planteome-core) and display that info on the 'Load Details' page?
Thanks

**Comment by cmungall** [comment]
not sure I understand. The list of ontologies loaded should match what is in the list of ontologies provided plus their import closure. No tweaking should be required

**Comment by elserj** [comment]
The golr_timestamp.log file only records the purl links, not the actual files that are grabbed via the catalog file.  I have a script that does the loading and uses sed to replace these, but it currently is somewhat hard-coded.  This issue is to generalize my script to use whatever the catalog file is actually loading.

**Comment by elserj** [comment]
Fixed loading script to use catalog file to replace links instead of hard coded ones.
