### ISSUE TITLE
Planteome: Search cassava germplasm annotations

### ISSUE THREAD

**Issue by jaiswalp** [Planteome/amigo#8]
http://dev.planteome.org/amigo/search/annotation?q=*:*&fq=assigned_by:%22marie-angelique_laporte%22&sfq=document_category:%22annotation%22

needs fixing the GAF annotation file.
- fill object name column. if no data available, replicate the info from object symbol column
- some direct annotation data shows up as TO ID vs others with TO term name. Not sure where the fault is. Whether it is so in the GAF file or it's a Amigo display issue

on this page
http://dev.planteome.org/amigo/gene_product/Genesys:CM840-177
the synonym should not have a hyperlink.

link the Genesys:CM840-177 hyperlinked to genesys database website.

**Comment by cooperl09** [comment]
I have modified the Cassava TO annotation file as follows:
I  copied the germplasm names to col 10: DB_Object_name, so that they will show up on the browser in the display and I also moved BMS_id values to DB_Object_Id (col2).  

http://palea.cgrb.oregonstate.edu/viewsvn/associations/to-associations/TO_germplasm_cassava_genesys.assoc?view=markup

The reason there are a few TO:ids showing up in the "Direct Annotation" column is those are newly added terms to the ontology and the ontology file has not been updated yet.  The version loaded on the browser is from 11-12-2015.  So this should resolve itself in the new release.
